### ISSUE TITLE
Data file source

### ISSUE THREAD

**Issue by Jiaotan8468** [qlt315/UCMEC-mmWave-Fronthaul#3]
Excuse me, is file address 
`data = hdf5storage.loadmat('./reward_list.mat')` in file  “scripts/data_process.py” this“train/reward.mat”？I can't find this file or the code file that generated it.

**Comment by qlt315** [comment]
Hi, ''data_process.py'' is used to smooth the reward curve and ''reward_list.mat'' is the reward raw data measured by this repository **manually** and imported to the Matlab. Since I haven't uploaded the raw data, you can ignore the ''data_process.py'' for now :).

**Comment by qlt315** [comment]
Hi, ''data_process.py'' is used to smooth the reward curve and ''reward_list.mat'' is the reward raw data measured by this repository **manually** and imported to the Matlab. Since I haven't uploaded the raw data, you can ignore the ''data_process.py'' for now :).

**Comment by Jiaotan8468** [comment]
I see. Thank you very much.
